### ISSUE TITLE
Build fails with  SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by andyrat33** [snyk/goof#796]
goof          | {"app":{},"services":{},"isLocal":true,"name":"goof","port":6001,"bind":"localhost","urls":["http://localhost:6001"],"url":"http://localhost:6001"}
goof          | Using Mongo URI mongodb://goof-mongo/express-todo
goof          | /usr/src/goof/node_modules/cli-highlight/node_modules/chalk/source/index.js:103
goof          | 	...styles,
goof          | 	^^^
goof          |
goof          | SyntaxError: Unexpected token ...
goof          |     at createScript (vm.js:56:10)
goof          |     at Object.runInThisContext (vm.js:97:10)
goof          |     at Module._compile (module.js:549:28)
goof          |     at Object.Module._extensions..js (module.js:586:10)
goof          |     at Module.load (module.js:494:32)
goof          |     at tryModuleLoad (module.js:453:12)
goof          |     at Function.Module._load (module.js:445:3)
goof          |     at Module.require (module.js:504:17)
goof          |     at require (internal/module.js:20:19)
goof          |     at Object.<anonymous> (/usr/src/goof/node_modules/cli-highlight/dist/theme.js:10:28)
goof          |     at Module._compile (module.js:577:32)
goof          |     at Object.Module._extensions..js (module.js:586:10)
goof          |     at Module.load (module.js:494:32)
goof          |     at tryModuleLoad (module.js:453:12)
goof          |     at Function.Module._load (module.js:445:3)
goof          |     at Module.require (module.js:504:17)

**Comment by FauxFaux** [comment]
Your node is too old. Please use a newer version of node.

**Comment by andyrat33** [comment]
Dockerfile has
FROM node:6-stretch

Please update the Dockerfile
